config/routes.rb
Rails.application.routes.draw do
  root 'forums#index'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy'
  get '/auth/:provider/callback' => 'session#omniauth', as: "omni"
  get '/forum/:id/close', to: 'forums#close', as: 'close'

  get '/forums/clear', to: 'forums#clear', as: 'clear'



  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
  resources :sessions
  resources :messages
  resources :posts

  resources :forums do
    resources :posts
  end

  resources :users do
    resources :posts, :forums
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/forum.rb
class Forum < ApplicationRecord
  has_many :posts
  has_many :users, :through => :posts
  belongs_to :user
  validates :name, presence: true
  accepts_nested_attributes_for :posts

  scope :most_recent, -> { order(created_at: :desc) }
  scope :active, -> { where(status: true)}
  scope :by_popularity, -> { Forum.left_joins(:posts).group(:id).order("count(posts.user_id) desc") }

  def d
    self.created_at.strftime("%m/%d/%Y, %I:%M%p")
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :forum

  validates :comment, presence: true

  scope :most_recent, -> { order(created_at: :desc) }

  def forum_name
    f = Forum.find_by(id:self.forum_id)
    f.name
  end

  def username
    u = User.find_by(id:self.user_id)
    u.username
  end

  def user
    u = User.find_by(id:self.user_id)
    u
  end

  def d
    self.created_at.strftime("%m/%d/%Y, %I:%M%p")
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts
  has_many :threads, foreign_key:"user_id", class_name: "Forum"
  has_many :messages
  has_many :forums, :through => :posts, source: :forums
  has_one_attached :avatar
  validates :username, :email, presence: true
  validates :username, :email, uniqueness: true

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.username = auth.info.name
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?
  private

  def redirect_if_not_logged_in
    redirect_to login_path if !logged_in?
  end

  def logged_in?
    !!current_user
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def clear_session(*args)
    args.each do |session_key|
      session[session_key] = nil
    end
  end
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController


  def index
    initialize_search
    handle_search_name
    handle_filters
  end

  def new
    @forum = Forum.new
    @forum.posts.build(comment: 'first post')
  end

  def create
    @forum = Forum.create(forum_params)
    if @forum.save
      params[:forum][:posts_attributes]["0"]["forum_id"] = @forum.id
      redirect_to forum_path(@forum.id)
    else
      render :new
    end
  end


  def clear
    clear_session(:search_name, :filter_name, :filter)
    redirect_to forums_path
  end

  def show
    @forum = Forum.find_by(id: params[:id])
  end

  def edit
    @forum = Forum.find_by(id: params[:id])
  end

  def update
    @forum = Forum.find_by(id: params[:id])
    if @forum.update(forum_params)
      redirect_to forum_path(@forum)
    else
      render :edit
    end
  end

  def close
    @forum = Forum.find_by(id: params[:id])
    @forum.update_attribute(:status, false)
    redirect_to forum_path(@forum.id)

  end


  def destroy
  end

  private
    def forum_params
      params.require(:forum).permit(:name, :user_id, :status, :category,
      posts_attributes: [
        :comment,
        :user_id,
        :forum_id
        ])
    end

  def initialize_search
    @forums = Forum.all
    session[:search_name] ||= params[:search_name]
    session[:filter] = params[:filter]
    params[:filter_option] = nil if params[:filter_option] == ""
    session[:filter_option] = params[:filter_option]
  end

  def handle_search_name
    if session[:search_name]
      @forums = Forum.where("name LIKE ?", "%#{session[:search_name]}%")

    else
      @forums = Forum.all
    end
  end

  def handle_filters
    if session[:filter_option] && session[:filter] == "most_recent"
      @forums = Forums.most_recent
    elsif session[:filter_option] && session[:filter] == "category"
      @forums = Forum.where(category: session[:filter_option])
    elsif session[:filter_option] && session[:filter] == "by_popularity"
      @forums = Forum.by_popularity
    elsif session[:filter_option] && session[:filter] == "active"
      @forums = Forums.active
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @forum = Forum.find(params[:forum_id])
    @post = @forum.posts.create(post_params)
    @post.user_id = current_user.id if current_user
    if @post.save
      redirect_to forum_path(@forum)
    else
      render :new
    end
  end


  def show
    @user = User.find_by(id: params[:id])
  end


  private

  def post_params
    params.require(:post).permit(:comment)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController


  def index
  end

  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user.id)
      else
        flash[:message] = "Sorry, your input was wrong or does not exist, please try again."
        render :new
      end
  end

  def destroy
    session.delete("user_id")
    redirect_to root_path
  end

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user.id)
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController

  def home
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #skip_before_action :redirect_if_not_logged_in, only: [:new, :create]
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end


  private
  def user_params
    params.require(:user).permit(:username, :password, :email, :avatar, :age, :fav_exercise, :gym)
  end
end

app/views/forums/_form.html.erb
<%= render partial: "layouts/errors", locals: { object: @forum } %>
<%= form_for @forum do |f| %>
  <%= f.label "Forum name" %>
  <%= f.text_field :name %>
  <%=f.label "Category" %>
  <%= f.select(:category, options_for_select([["Exercise","Exercise"],["Workout","Workout"],["Diet","Diet"],["Competition","Competition"]]))%>
  <%= f.hidden_field :user_id, value:current_user.id %><br>
  <br>
  <%= f.fields_for :posts do |p|%>
    <%= p.label "Content:" %>
    <%= p.text_area :comment %>
    <%= p.hidden_field :user_id, value:current_user.id %>
    <%= p.hidden_field :forum_id, value: @forum.id%>
    <%end%>
<br>
  <%=f.submit%>
<%end%>

app/views/forums/index.html.erb
<% if !current_user %>
<div class="welcome">
<h1> Welcome to the Forum please login or signup!</h1>
</div>
<%else%>
<div class="banner">
<h3> Forums </h3>
<form action="/forums" method="GET">
  <input type="text" name="search_name" >
  <input type="submit" value="Search for Forum">
</form>

<form action="/forums" method="GET">
  <label for="filter">Filter Options</label>
  <select id="filter" name="filter" onchange="this.form.submit()">
    <option value="">Pick a Filter Option</option>
    <option value="category" <%= "selected" if session[:filter] == "category" %>>Filter by Category</option>
    <option value="most_recent" <%= "selected" if session[:filter] == "most_recent" %>>Filter by Most Recent</option>
    <option value="by_popularity" <%= "selected" if session[:filter] == "by_popularity" %>>Filter by Popularity</option>
    <option value="active" <%= "selected" if session[:filter] == "active" %>>Active Forums</option>
  </select>
  <% if session[:filter] == "" %>
    <%=@forums = Forum.all%>
  <% elsif session[:filter] == "category" %>
    <select name="filter_option" onchange="this.form.submit()">
      <option value="">Pick a Category</option>
      <option value="Exercise">Exercise</option>
      <option value="Workouts">Workouts</option>
      <option value="Diet">Diet</option>
      <option value="Competition">Competition</option>
    </select>
  <% elsif session[:filter] == "most_recent" %>
    <select name="filter_option" onchange="this.form.submit()">
      <%= @forums = Forum.all.most_recent %>
    </select>
  <% elsif session[:filter] == "by_popularity" %>
    <select name="filter_option" onchange="this.form.submit()">
      <%= @forums = Forum.all.by_popularity %>
    </select>
  <% elsif session[:filter] == "active" %>
     <select name="filter_option" onchange="this.form.submit()">
       <%= @forums = Forum.all.active %>
     </select>
  <% end %>
</form>
</div>
<br>
<div class="clear">
<%= link_to "Clear Filter Options", clear_path %>
</div>

<div class="inner-main-body">
  <%if @forums.empty? %>
  <div class="banner">
  <strong>There are no forums, please pick a different category</strong>
  <%end%>
</div>
<% @forums.each do |forum| %>
<div class="row">
  <div class="col-md-6">
    <div class="card mb-2">
        <div class="card-body">
          <image src="<%=(url_for(forum.user.avatar))%>" class="rounded-circle" width="50" alt="User" />
        <strong> <%= link_to forum.name, forum_path(forum)%></strong> - created by - <%=link_to forum.user.username, user_path(forum.user)%><br>
        <strong><%= forum.category%></strong>
        <br>
        <%= forum.users.uniq.count%> users in conversation
        <br>
          <p>posted <%= time_ago_in_words(forum.created_at) %> ago, most recent post: <%= time_ago_in_words(forum.posts.last.created_at)%> ago</p
          <br>


  </div>
</div>
  </div>
</div>

<%end%>
<%end%>
</div>

app/views/forums/new.html.erb
<div class="banner">
<h1> Create A New Thread </h1>
</div>
<div class="thread">
<%= render partial: "form", locals: { object: @form } %>
</div>

app/views/forums/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-2/css/all.min.css" integrity="sha256-46r060N2LrChLLb5zowXQ72/iKKNiw/lAmygmHExk/o=" crossorigin="anonymous" />
<div class="container">
<div class="col-md-3-align-self-center">
<div class="inner-main-body">
    <div class="card mb-2">
        <div class="card-body">
            <div class="media forum-item">
                <a href="<%=user_path(@forum.user_id)%>" class="card-link">
                    <image src="<%=(url_for(@forum.user.avatar))%>" class="rounded-circle" width="50" alt="User" />

                </a>
                <div class="media-body ml-3">
                    <a href="<%=user_path(@forum.user_id)%>" class="text-secondary"><%=@forum.user.username%></a>
                    <small class="text-muted ml-2">posted <%= time_ago_in_words(@forum.created_at) %> ago</small>
                    <h5 class="mt-1"><%=@forum.name%></h5>
                    <div class="mt-3 font-size-sm">
                    <p><%=@forum.posts.first.comment%></p>
                    </div>
                </div>
                <div class="text-muted small text-center">
                    <span><i class="far fa-comment ml-2"></i><%= @forum.posts.count%></span>
                </div>
            </div>
        </div>
    </div>
    <% @forum.posts.drop(1).each do |post| %>
    <div class="card mb-2">
        <div class="card-body">
            <div class="media forum-item">
                <a href="<%=user_path(post.user_id)%>" class="card-link">
                    <image src="<%=(url_for(post.user.avatar))%>" class="rounded-circle" width="50" alt="User" />
                </a>
                <div class="media-body ml-3">
                    <a href="<%=user_path(post.user_id)%>" class="text-secondary"><%=post.user.username%></a>
                    <div class="mt-3 font-size-sm">
                    <p><%=post.comment%></p>
                    <small class="text-muted ml-2">posted <%= time_ago_in_words(post.created_at)%> ago</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%end%>
</div>


</div>



<% if @forum.status == true %>
<div class="banner">
  <%= render 'posts/form'%>
</div>
  <footer>
  <% if @forum.user_id == session[:user_id] %>
  <button type="button" class="btn btn-warning"><%=link_to "Close Thread", close_path(@forum)%></button>
  <%end%>
  </footer>
<%else %>
  <footer>
  <button type="button" class="btn btn-warning" disabled>  <strong>This Forum Is Closed.</strong></button>
    </footer>
<%end%>

app/views/layouts/_errors.html.erb
<% if object.try(:errors).try(:any?) %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="header"
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
       <svg class="bi me-2" width="40" height=5 role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
     </a>
     <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">

        <% if !current_user %>
          <div class="d-flex justify-content-center py-3">
            <a type="button" class="btn btn-outline-primary me-2" href="<%=new_user_path%>"/>Sign Up</a>
            <a type="button" class="btn btn-outline-primary me-2" href="<%='/auth/google_oauth2'%>"/>Signup/Login with Google</a>
            <a type="button" class="btn btn-primary" href="<%= login_path %>"/>Login</a>
          </div>
          <% end %>
          <% if current_user %>
        <li>  <a class="nav-link px-2 link-secondary" href="<%= root_url %>"/>Home</a></li>
        <li>  <a class="nav-link px-2 link-dark"" href="<%= user_path(current_user)%>"/>Your Profile</a></li>
        <li>  <a class="nav-link px-2 link-dark" href="<%= users_path%>"/>All Users</a></li>
        <li>  <a class="nav-link px-2 link-dark" href="<%= posts_path%>"/>All Posts</a></li>
        <li>
          <%if current_user %>
          <a type="button" class="btn btn-light" <%=link_to "New Forum", new_user_forum_path(current_user)%></a></li>
          <%end%>
        <li><a type="button" class="btn btn-primary"  <%= link_to "Log Out", logout_path, method:'delete', data: { confirm: 'Logout?' }%></a></li>
          <% end %>
          </ul>
    </div>
    </div>
    <!-- content -->

    <div class="inner-main-body"  role="main">
      <%= yield %>
    </div>
  </body>
  <br>
  <br>

</html>

app/views/posts/_form.html.erb
<%= form_for ([@forum, @forum.posts.build]) do |p| %>
<%= p.label :comment %>
<%= p.text_area :comment %>
<%= p.hidden_field :user_id, value:current_user.id %>
<%= p.hidden_field :forum_id, value:@forum.id%>
<%= p.submit %>
<%end%>

app/views/posts/index.html.erb
<% @posts.each do |post|%>
<div class="card mb-2">
    <div class="card-body">
      <ul>
      <p><strong><%= post.comment %></strong> <%=post.d%><p>
        <li>Found in: <%= link_to post.forum_name, forum_path(post.forum_id) %></li>
        <li>Written by: <%= link_to post.username, user_path(post.user_id) %></li>
      </ul>
    </div>
</div>
<%end%>

app/views/posts/new.html.erb
<%= render partial: "layouts/errors", locals: { object: @post } %>
<%= form_for ([@forum, @forum.posts.build]) do |p| %>
<%= p.label :comment %>
<%= p.text_field :comment %>
<%= p.hidden_field :user_id, value:current_user.id %>
<%= p.hidden_field :forum_id, value:@forum.id%>
<%= p.submit %>
<%end%>

app/views/posts/show.html.erb
<% @user.posts.each do |post|%>
<div class="card mb-2">
    <div class="card-body">
      <ul>
        <p><strong><%= post.comment %> <%=post.d%></strong><p>
        <li>Found in: <%= link_to post.forum_name, forum_path(post.forum_id) %></li>
        <li><%= time_ago_in_words(post.created_at) %> ago</li>
      </ul>
    </div>
</div>
<%end%>

app/views/session/new.html.erb
<div class="wrapper">
<h1> Please Login </h1>

<% if flash[:message] %>
  <%= flash[:message] %>
<%end%>

<%= form_for :user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
<br>
  <%= f.label :password %>
  <%= f.password_field :password %>

  <%=f.submit "Log In"%>
<%end%>
</div>

app/views/users/edit.html.erb
<div class="banner">
   <div class="span6 offset3">
<h1>Edit Your Stats!</h1>
<%= render partial: "layouts/errors", locals: { object: @user } %>
<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>
 <fieldset>
  <div class = "form-group">
  <%= f.label :username, :class => "col-sm-2 control-label" %>
  <div class = "col-sm-10">
  <%= f.text_field :username,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :email, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :email,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :age, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.number_field :age,:class => "form-control" %><br>
  </div>
  </div>
  <div class = "form-group">
  <%= f.label :fav_exercise, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :fav_exercise,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :gym, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :gym ,:class => "form-control"%><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label "Profile Photo", :class => "col-sm-4 control-label" %>
  <div class = "col-sm-10">
  <%= f.file_field :avatar,:class => "form-control"%><br>
  </div>
  </div>

   <div class = "form-actions">
  <%=f.submit "Update!"%>
<%end%>
</div>
</div>

app/views/users/index.html.erb
<div class="banner">
<h1> A List of All Users </h1>
</div>
<br>

<% @users.each do |user| %>
<div class="col-9">
    <div class="col-6">
      <ul>
        <% if user.avatar.attached?%>
          <p><image src="<%=(url_for(user.avatar))%>" class="rounded-circle" width="100" alt="User" /></p>
          <%end%>
        <li><%= link_to user.username, user_path(user)%>

        </li>
      </ul>
    </div>
</div>
<%end %>

app/views/users/new.html.erb
<div class="banner">
<h1>Please Signup here!</h1>
<%= render partial: "layouts/errors", locals: { object: @user } %>
 <div class="span6 offset3">
<%= form_for(@user, :html => {:class => 'form-horizontal'}) do |f| %>
 <fieldset>
  <div class = "form-group">
  <%= f.label :username, :class => "col-sm-2 control-label" %>
  <div class = "col-sm-10">
  <%= f.text_field :username,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :email, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :email,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :password, :class => "col-sm-2 control-label" %>
  <div class = "col-sm-10">
  <%= f.password_field :password,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :age, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.number_field :age,:class => "form-control" %><br>
  </div>
  </div>
  <div class = "form-group">
  <%= f.label :fav_exercise, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :fav_exercise,:class => "form-control" %><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label :gym, :class => "col-sm-2 control-label"; %>
  <div class = "col-sm-10">
  <%= f.text_field :gym ,:class => "form-control"%><br>
  </div>
  </div>

  <div class = "form-group">
  <%= f.label "Profile Photo", :class => "col-sm-4 control-label" %>
  <div class = "col-sm-10">
  <%= f.file_field :avatar,:class => "form-control"%><br>
  </div>
  </div>

   <div class = "form-actions">
  <%=f.submit "Signup"%>
<%end%>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <div class="banner">
      <%if session[:user_id] == @user.id %>
          <h2>Your Profile</h2>

          <% if @user.avatar.attached?%>
          <p><image src="<%=(url_for(@user.avatar))%>" class="rounded-circle" width="100" alt="User" /></p>
            <%else%>
              <%= form_for @user do |f| %>
                <%= f.label "Add A Profile Photo" %>
                <%= f.file_field :avatar%><br>
                <%=f.submit "Add"%>
              <%end%>
            <%end%>

      <%else%>
          <h2> <%=@user.username%>'s Profile </h2>
          <% if @user.avatar.attached?%>
            <p><image src="<%=(url_for(@user.avatar))%>" class="rounded-circle" width="100" alt="User" /></p>
            <%end%>
        <%end%>
        </div>
    </div>
<br>
<br>
  <div class="col-4">
    <h4>Stats</h4>
    <p>Age: <%=@user.age%></p>
    <p>Favorite Exercise: <%=@user.fav_exercise%></p>
    <p>Gym: <%=@user.gym%></p>
    <p>Total Posts: <%=@user.posts.count%></p>
      <%if session[:user_id] == @user.id %>
      <small><%=link_to "Edit Stats", edit_user_path(@user)%></small>
      <%end%>
    </div>
    <div class="col-6">
      <h3> Created Threads </h3>
        <ol>
        <% @user.threads.each do |thread| %>
          <li><%=link_to thread.name, forum_path(thread)%></li><br>
        <%end%>
        </ol>
          <h4><%=link_to 'All Posts Made By User', user_post_path(@user)%></h4>
        <br>
    </div>
</div>

<br>
<footer>
<%if session[:user_id] == @user.id %>

<button type="button" class="btn btn-light btn-lg btn-block""><%=link_to "New Forum", new_user_forum_path(@user)%></button>
<%end%>
</footer>
</div>